services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    - ./source:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data/freescout:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - ./data/logs/:/www/logs
    expose:
      - 80
    environment:
      - CONTAINER_NAME=freescout-app

      - DB_HOST=${DB_HOST:-freescout-db}
      - DB_NAME=${DB_NAME:-freescout}
      - DB_USER=${DB_USER:-freescout}
      - DB_PASS=${DB_PASS:-freescout}

      - SITE_URL=https://${DOMAIN:?missing DOMAIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL:?missing ADMIN_EMAIL}
      - ADMIN_PASS=${ADMIN_PASSWORD:?missing ADMIN_PASSWORD}
      - ENABLE_SSL_PROXY=${ENABLE_SSL_PROXY:-FALSE}
      - DISPLAY_ERRORS=${DISPLAY_ERRORS:-FALSE}
      - TIMEZONE=${TIMEZONE:-UTC}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freescout.entrypoints=websecure"
      - "traefik.http.routers.freescout.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.freescout.tls.certresolver=http-challenge"
    networks:
      - traefik-proxy
      - default
    restart: always
  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - ROOT_PASS=${MYSQL_ROOT_PASSWORD:?missing MYSQL_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME:-freescout}
      - DB_USER=${DB_USER:-freescout}
      - DB_PASS=${DB_PASS:-freescout}

      - CONTAINER_NAME=freescout-db
    networks:
      - default
    restart: always
  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    volumes:
      - ./data/dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=${DB_HOST:-freescout-db}
      - DB_TYPE=mariadb
      - DB_NAME=${DB_NAME:-freescout}
      - DB_USER=${DB_USER:-freescout}
      - DB_PASS=${DB_PASS:-freescout}
      - DB_DUMP_FREQ=${DB_DUMP_FREQ:-1440}
      - DB_DUMP_BEGIN=$DB_DUMP_BEGIN:-0000}
      - DB_CLEANUP_TIME=${DB_CLEANUP_TIME:-8640}
      - COMPRESSION=${COMPRESSION:-BZ}
      - MD5=${MD5:-TRUE}
    networks:
      - default
    restart: always
networks:
  default:
  traefik-proxy:
    external: true
    name: traefik-proxy
